export const BRAND = {
  name: "Gritly",
  tagline: "Built for grit.",
  description: "The field service platform that replaces Jobber, CompanyCam, and 4 other tools — with unlimited users on every plan.",
  url: "https://grit.ly",
  email: "gritlyteam@gmail.com",
  parent: "OASIS AI Solutions",
  parentUrl: "https://oasisai.work",
} as const;

export const PRICING = {
  starter: {
    name: "Starter",
    price: 79,
    priceAnnual: 59,
    users: "Unlimited",
    description: "Everything a solo operator needs to look professional and get paid faster.",
    cta: "Start Free Trial",
    features: [
      "Unlimited users",
      "Client management (CRM)",
      "Quoting & invoicing",
      "Drag-and-drop scheduling",
      "Online booking widget",
      "Client portal",
      "Mobile app (iOS & Android) (Coming soon)",
      "GPS job tracking",
      "Job photos & documentation",
      "Basic reporting",
      "Email & SMS reminders",
      "Online payments (card, ACH)",
    ],
  },
  pro: {
    name: "Pro",
    price: 179,
    priceAnnual: 139,
    users: "Unlimited",
    description: "For growing teams that need automation, routing, and job costing.",
    cta: "Start Free Trial",
    popular: true,
    features: [
      "Everything in Starter",
      "Smart scheduling & dispatch",
      "Job costing & profitability",
      "Flat-rate pricebook",
      "Two-way SMS inbox",
      "Automated quote follow-ups",
      "Automated invoice reminders",
      "QuickBooks & Xero sync (Coming soon)",
      "Time tracking & timesheets",
      "Custom checklists & forms",
      "Expense tracking with receipts",
      "Job photos & documentation",
      "Review request automation",
      "Offline mobile mode (Coming soon)",
    ],
  },
  business: {
    name: "Business",
    price: 299,
    priceAnnual: 229,
    users: "Unlimited",
    description: "For operations that run multiple crews and need full visibility.",
    cta: "Start Free Trial",
    features: [
      "Everything in Pro",
      "AI receptionist (Coming soon)",
      "Advanced reporting & forecasting",
      "Custom automation builder",
      "Maintenance agreements",
      "Progress billing & milestones",
      "Inventory & parts tracking",
      "Subcontractor management",
      "Marketing attribution",
      "Consumer financing (Coming soon)",
      "API access",
      "Dedicated success manager",
      "Priority support",
    ],
  },
} as const;

export const INDUSTRIES = [
  { slug: "hvac", name: "HVAC", icon: "Thermometer", tagline: "From emergency calls to maintenance plans — run your HVAC business from one place." },
  { slug: "plumbing", name: "Plumbing", icon: "Wrench", tagline: "Emergency dispatch, permit tracking, and invoicing that keeps your cash flowing." },
  { slug: "electrical", name: "Electrical", icon: "Zap", tagline: "Panel docs, permit tracking, and scheduling that keeps your crews moving." },
  { slug: "painting", name: "Painting", icon: "Paintbrush", tagline: "Room-by-room estimating, color tracking, and crew management built for painters." },
  { slug: "landscaping", name: "Landscaping", icon: "TreePine", tagline: "Route optimization, chemical tracking, and seasonal contracts on autopilot." },
  { slug: "roofing", name: "Roofing", icon: "Home", tagline: "Aerial measurements, material takeoffs, and milestone billing for every roof." },
  { slug: "cleaning-residential", name: "Residential Cleaning", icon: "Sparkles", tagline: "Recurring schedules, checklists, and auto-charge that keep your clients coming back." },
  { slug: "cleaning-commercial", name: "Commercial Cleaning", icon: "Building", tagline: "Multi-location management, shift scheduling, and inspection reports at scale." },
  { slug: "general-contracting", name: "General Contracting", icon: "HardHat", tagline: "Subcontractor management, progress billing, and permit tracking for every project." },
  { slug: "pest-control", name: "Pest Control", icon: "Bug", tagline: "Chemical compliance, trap monitoring, and route optimization for every technician." },
  { slug: "pool-service", name: "Pool Service", icon: "Waves", tagline: "Water chemistry logs, equipment tracking, and recurring routes that run themselves." },
  { slug: "pressure-washing", name: "Pressure Washing", icon: "Droplets", tagline: "Square footage estimating, before/after photos, and fast invoicing." },
  { slug: "window-cleaning", name: "Window Cleaning", icon: "Maximize", tagline: "Pane counting, route optimization, and recurring schedules for every property." },
  { slug: "handyman", name: "Handyman", icon: "Hammer", tagline: "Multi-skill job types, material lists, and time tracking for every project." },
] as const;

export type IndustrySlug = typeof INDUSTRIES[number]["slug"];
